### ISSUE TITLE
Does MMM-SleepWake work with the Jetson Nano?

### ISSUE THREAD

**Issue by Dresch360** [sdetweil/MMM-SleepWake#5]
I have the latest version of MagicMirror (2.15) running on a Jetson Nano running Ubuntu 18.04 with Jetpack 4.2.0 using Pi V2 camera running/working, as well as MMM-Gestures, as well as many other modules. 

The monitor shuts off after the correct time period via dpms using MMM-SleepWake, but doesn't turn power back on with motion and I see a grey box at localhost:8081 and "UNABLE TO OPEN VIDEO DEVICE". However the Pi camera works fine with nvgstcapture. Do you know if there is special setting needed in the /etc/motion/motion.conf file?

Any help or suggestions would be greatly appreciated!

**Comment by sdetweil** [comment]
yes it does, I have one.
I didn't do anything special. just plugged in my webcam and motion detected it

**Comment by sdetweil** [comment]
according to motion doc 

Raspberry Pi cameras can be set up two different ways. If Motion is installed by using the apt packages (e.g. apt-get install motion), **then the camera must be set up using the bcm2835-v4l2** module which creates a v4l2 device for the camera. Users will need to install this module using the command sudo modprobe bcm2835-v4l2. This will set up the camera as a normal v4l2 device and it can be accessed via a standard /dev/videoX device. If Motion is built from source or installed via the deb packages on the project release page, then an additional option is to set up the camera using the mmalcam_name parameter or using the bcm2835-v4l2 module. When Motion is installed via apt, the mmalcam option is not available.

**Comment by Dresch360** [comment]
Thanks for your quick response and you are 100% correct. It does work out of the box with the USB cam and I had my settings incorrect for the Pi Cam. Thanks again for all of your help!
